version: '2'
services:
  a:
    image: tutum/hello-world
    networks:
      - frontend
  b:
    image: tutum/hello-world
    networks:
      - frontend
      - backend
  c:
    image: tutum/hello-world
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
